config/routes.rb
Rails.application.routes.draw do
  
  resources :posts
  
  resources :posts2

  resources :posts3
  
  get 'bousai/index' => 'bousai#index'
  get 'bousai/new' => 'bousai#new'
  get 'bousai/show' => 'bousai#show'
  resources :bousai
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root 'tweets#index'
get 'tweets/new' => 'tweets#new'
post 'tweets' => 'tweets#create'
get 'tweets/:id' => 'tweets#show' ,as: 'tweet'
patch 'tweets/:id' => 'tweets#update'
delete 'tweets/:id' => 'tweets#destroy'
get 'tweets/:id/edit' => 'tweets#edit', as:'edit_tweets'

resources :tweets


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bousai_quiz.rb
class BousaiQuiz < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/post2.rb
class Post2 < ApplicationRecord
end

app/models/post3.rb
class Post3 < ApplicationRecord
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/quiz.rb
class Quiz < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true
  #Tagsテーブルから中間テーブルに対する関連付け
  has_many :tweet_tag_relations, dependent: :destroy
  #Tagsテーブルから中間テーブルを介してArticleテーブルへの関連付け
  has_many :tweets, through: :tweet_tag_relations, dependent: :destroy
end

app/models/tweet.rb
class Tweet < ApplicationRecord
#tweetsテーブルから中間テーブルに対する関連付け
has_many :tweet_tag_relations, dependent: :destroy
#tweetsテーブルから中間テーブルを介してTagsテーブルへの関連付け
has_many :tags, through: :tweet_tag_relations, dependent: :destroy
has_one_attached :image
end

app/models/tweet_tag_relation.rb
class TweetTagRelation < ApplicationRecord
  belongs_to :tweet
  belongs_to :tag
end

app/controllers/bousai_controller.rb
class BousaiController < ApplicationController
   def index
   end

   

end

app/controllers/posts2_controller.rb
class Posts2Controller < ApplicationController
  def index
    food = params[:food]
    water = params[:water]
    toilet = params[:toilet]
    bousai_no_hi = params[:bousai_no_hi]
    equipment = params[:equipment]
   
    @result = food + water + toilet + bousai_no_hi + equipment
    @posts2 = Post2.all
  end
end

app/controllers/posts3_controller.rb
class Posts3Controller < ApplicationController
  def index
    shoes = params[:shoes]
    evacuation_level = params[:evacuation_level]
    evacuation_timing = params[:evacuation_timing]
    knee = params[:knee]
    raincoat = params[:raincoat]
   
    @result = shoes + evacuation_level + evacuation_timing + knee + raincoat
    @posts3 = Post3.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
 
def index
  elevator = params[:elevator]||0
  inside = params[:inside]||0
  alert = params[:alert]||0
  dial = params[:dial]||0
  fixing = params[:fixing]||0
 
  @result = elevator + inside + alert + dial + fixing
  @posts = Post.all
end


end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
  end

  def new
    @tweet = Tweet.new
  end

  def create
    tweet = Tweet.new(tweet_params)
    if tweet.save
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    if tweet.update(tweet_params)
      redirect_to :action => "show", :id => tweet.id
    else
      redirect_to :action => "new"
    end
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to action: :index
  end

  private
  def tweet_params
    params.require(:tweet).permit(:genre, :place, :about, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bousai_helper.rb
module BousaiHelper
end

app/helpers/bousais_helper.rb
module BousaisHelper
end

app/helpers/posts2_helper.rb
module Posts2Helper
end

app/helpers/posts3_helper.rb
module Posts3Helper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/bousai/index.html.erb
<!DOCTYPE html> <!--　この文章がHTML文章であることを伝える要素です。-->
<html lang="ja"><!--言語の指定-->
    <head><!--ページに表示されない情報(サイトの裏側の設定)-->
        <meta charset="utf-8">
        <title>防災クイズスタート</title><!--ブラウザのタブのタイトルを指定-->
    </head>

    <body>
        <header>
            <h1 class="headline">
            <a>防災</a>
            </h1>
            <h2> 防災クイズ </h2>
            <ul class="nav-list">
                
                <li class="nav-list-item"><%= link_to "～地震編～", new_post_path, class: "link" %></li>
                <li class="nav-list-item"><%= link_to "～豪雨編～", new_posts3_path, class: "link" %></li>
                <li class="nav-list-item"><%= link_to "～防災その他編～", new_posts2_path, class: "link" %></li>
            </ul>
        </header>

        <div class="start">
            <h2>私の防災</h2>
            <%= link_to "投稿・閲覧はこちらへ", tweets_path, class: "link" %>
        </div>
    </body>

app/views/bousai/new.html.erb
 <%= form_tag(bousai_new_path, method: :get) do %>
    <div class="container-sindan">
    <div class="row">
        
        <p>Q.1 エレベータに乗っているときに地震が発生しました。一番にすることは何ですか？</p>
        <label>
            <%= radio_button_tag :elevator, "1", nil %> 一番近い階のボタンだけを押す
        </label>
        <label>
            <%= radio_button_tag :elevator, "2" , nil%> 全ての階のボタンを押す
        </label>
        <label>
            <%= radio_button_tag :elevator, "3", nil %> 一階のボタンを押す
        </label>
        

    <p>Q.2 屋内で地震が発生しました。まず何をしますか</p>
        <label>
            <%= radio_button_tag :inside, "1", nil %> すぐに外へ逃げだす
        </label>
        <label>
            <%= radio_button_tag :inside, "2", nil %> その場にしゃがんで頭を守る
        </label>
        <label>
            <%= radio_button_tag :inside, "3", nil %> 情報を調べるためにスマホを探す
        </label>

    <p>Q.3 緊急地震速報がなったとき、何をしますか。</p>
        <label>
            <%= radio_button_tag :alert, "1", nil %> テーブルなどの下に入り、低い姿勢を取る
        </label>
        <label>
            <%= radio_button_tag :alert, "2", nil %> アラームを止める
        </label>
        <label>
            <%= radio_button_tag :alert, "3" , nil%> 外へ逃げるために窓の近くに行く
        </label>
    
    <p>Q.4 災害用伝言ダイヤルの番号はどれでしょう？</p>
        <label>
            <%= radio_button_tag :dial, "1", nil %> 171
        </label>
        <label>
            <%= radio_button_tag :dial, "2" , nil%> 118
        </label>
        <label>
            <%= radio_button_tag :dial, "3" , nil%> 188
        </label>

    <p>Q.5 自分の家の家具を固定していますか？</p>
        <label>
            <%= radio_button_tag :fixing, "1" , nil%> はい
        </label>
        <label>
            <%= radio_button_tag :fixing, "2", nil %> いいえ
        </label>

    </div>
    </div>
    
    <div class="sindanbotan">           
     <%= submit_tag "回答完了" %>
    </div>
    <%= link_to '回答完了', bousai_show_path %>

 <% end %>

app/views/posts/index.html.erb
<% @posts.each do |t| %>
    <% if t.number == @result %>
        <div class="tweet">
            あなたは<%= t.content %>
        </div>
    <% end %>
<% end %>

<%= link_to 'トップページ', bousai_index_path %>

app/views/posts/new.html.erb
 <%= form_tag(posts_path, method: :get) do %>
    <h3>Q.1 エレベータに乗っているときに地震が発生しました。一番にすることは何ですか？</h3>
        <label>
            <%= radio_button_tag :elevator, "1" %> 一番近い階のボタンだけを押す
        </label>
        <label>
            <%= radio_button_tag :elevator, "2" %> 全ての階のボタンを押す
        </label>
        <label>
            <%= radio_button_tag :elevator, "3" %> 一階のボタンを押す
        </label>
        

    <h3>Q.2 屋内で地震が発生しました。まず何をしますか</h3>
        <label>
            <%= radio_button_tag :inside, "1" %> すぐに外へ逃げだす
        </label>
        <label>
            <%= radio_button_tag :inside, "2" %> その場にしゃがんで頭を守る
        </label>
        <label>
            <%= radio_button_tag :inside, "3" %> 情報を調べるためにスマホを探す
        </label>

    <h3>Q.3 緊急地震速報がなったとき、何をしますか。</h3>
        <label>
            <%= radio_button_tag :alert, "1" %> テーブルなどの下に入り、低い姿勢を取る
        </label>
        <label>
            <%= radio_button_tag :alert, "2" %> アラームを止める
        </label>
        <label>
            <%= radio_button_tag :alert, "3" %> 外へ逃げるために窓の近くに行く
        </label>
    
    <h3>Q.4 災害用伝言ダイヤルの番号はどれでしょう？</h3>
        <label>
            <%= radio_button_tag :dial, "1" %> 171
        </label>
        <label>
            <%= radio_button_tag :dial, "2" %> 118
        </label>
        <label>
            <%= radio_button_tag :dial, "3" %> 188
        </label>

    <h3>Q.5 自分の家の家具を固定していますか？</h3>
        <label>
            <%= radio_button_tag :fixing, "1" %> はい
        </label>
        <label>
            <%= radio_button_tag :fixing, "2" %> いいえ
        </label>

    <br>
    <%= submit_tag '回答完了'  %>
 <% end %>

app/views/tweets/edit.html.erb
<%= form_for @tweet do |f| %>
  <%= f.label :コメント %>
  <%= f.text_field :about, :size => 140 %> 
  <%= f.submit "編集する" %>
<% end %>

app/views/tweets/index.html.erb
<%= stylesheet_link_tag 'index', :media => "all" %>

<div class="tweets-container">
<h1>私の防災</h1>
<h3>投稿一覧</h3>
<%= link_to "新規投稿へ", new_tweet_path %>
<div class="tweets-container">
  <% @tweets.each do |t| %>
    <div class="tweet">
       <div class="main-box">
        <div class="left-container"><%= t.about %></div>
        <div class="right-container">
       <% if t.image.attached? %>
            <%= image_tag t.image, size: '250x200'%>
        <% end %>
      <%= t.genre %>
      <%= t.place%>
      <%= t.about %>
      <%= t.image %>
      <%= link_to "詳細へ", tweet_path(t.id) %>
      </div>
    <%= link_to "編集する", edit_tweets_path(t.id) %>
    <%= button_to "削除する", tweet_path(t.id), method: :delete %>
   </div>
    </div><p class="time"><%= t.created_at %></p>
    
  <% end %>
<%= link_to "トップページ", bousai_index_path %>
</div>

app/views/tweets/new.html.erb
<%= stylesheet_link_tag 'new', :media => "all" %>

<div class="post-container">
<h1>私の防災</h1>
<h3>新規投稿ページ</h3>
<%= form_for @tweet do |f| %>

# データ型がstringで自由記述の入力フォーム
  <div class="field">
    <%= f.label :シチュエーション %>
    <%= f.text_field :genre, :size => 140 %>
  </div>

# データ型がstringで選択式の入力フォーム
  <div class="field">
    <%= f.label :場所  %>
    <%= f.select :place, 
    [["家", "家"], 
    ["屋内（家以外）", "屋内（家以外）"], 
    ["屋外", "屋外"]], include_blank: "選択して下さい" %>
  </div>

# データ型がtextで自由記述の入力フォーム
  <div class="field">
    <%= f.label :コメント  %>
    <%= f.text_area :about, :size => "30x2" %>
  </div>

 # データ型がstringで自由記述の入力フォーム
  <div class="field">
    <%= f.label :画像 %>
    <%= f.file_field :image, :size => 140 %>
  </div>

  <%= f.submit "投稿する" %>
<% end %>

<%= link_to "一覧に戻る", tweets_path %>

</div>

app/views/tweets/show.html.erb
<h1>GeekTwitter</h1>
<h3>Tweet詳細</h3>
<div class="tweet">
  <p><%= @tweet.about %></p>
  <p><%= @tweet.created_at %></p>
</div>

<%= link_to "Tweet一覧に戻る", tweets_path %>